Configure gsoci.azurecr.io as the registry to use by default
giantswarm/falco-app pull request #196
Opened 2023-12-20 10:59 UTC by marians

Towards

- https://github.com/giantswarm/roadmap/issues/3017

This PR replaces any occurrence of `docker.io` in `values.yaml` files with `gsoci.azurecr.io`,
to make the new ACR registry the default one.

2023-12-20 14:00 UTC, marians commented
@giantswarm/team-shield In this case I wasn't really sure which images can be pulled from `gsoci.azurecr.io` and which ones have to come from docker.io. I only changed the ones that have the `giantswarm/` namespace prefix.

2024-01-10 17:16 UTC, Strigix requested changes
The upstream charts don't need their image set, this will be overwritten by our app-level values.yaml.

2024-01-10 17:22 UTC, Strigix approved these changes

2024-01-10 17:23 UTC, merged

2024-01-12 09:23 UTC, Strigix commented
I'll do a quick test to see if it pulls like it should, if yes. I'll release a patch today 🥳